version: "3"

services:
  amazon_linux:
    container_name: amazon_linux
    image: amazonlinux
    tty: true
    # volumes:
    #   - ./src:/var/www/src:cached
    # working_dir: /var/www/src
    # depends_on:
