version: "3"

services:
  amazon_linux:
    container_name: amazon_linux
    build: ./containers
    tty: true
    stdin_open: true
    ports:
      - "2022:22"
      - "8080:80"
      - "4043:443"

    # volumes:
    #   - ./src:/var/www/src:cached
    # working_dir: /var/www/src


