FROM amazonlinux:2

# RUN yum -y update
RUN yum -y install sudo

# ##### ps command
# RUN sudo yum -y install procps

# ##### tmp
# RUN echo "PHP Installing..."
# RUN amazon-linux-extras enable php8.0
# RUN sudo yum install -y php
# # RUN sudo yum install -y php-bcmath php-dom php-gd php-mbstring php-mysqli php-posix php-sodium php-opcache

# RUN echo "Composer Installing..."
# RUN sudo curl -sS https://getcomposer.org/installer | sudo php
# RUN sudo mv composer.phar /usr/local/bin/composer
# RUN sudo ln -s /usr/local/bin/composer /usr/bin/composer
