---
- hosts: localhost
  become: true
  tasks:
    - name: Installing Remi Repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

  #   - name: Installing php
  # yum:
  #   enablerepo: "remi,remi-php80" # If you intent to install a different version of PHP, you can change the repo according. Eg : "remi,remi-php74"
  #   name:
  #   - php
  #   - php-common
  #   - php-cli
  #   - php-gd
  #   - php-curl #You can add or remove PHP extensions according to your choice
  #   - php-mysqlnd
  #   - php-fpm
  #   - php-mysqli
  #   state: latest


    # - name: PHP
    #   yum: name=epel-release state=installed

    # - name: add remi-repo repository
    #   command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

    # - name: install php 7.2
    #   yum: name={{ item }} enablerepo=remi,remi-php72 state=installed
    #   with_items:
    #     - php
    #     - php-devel
    #     - php-fpm
    #     - php-gd
    #     - php-mbstring
    #     - php-mcrypt
    #     - php-mysqlnd
    #     - php-mysql
    #     - php-pdo
    #     - php-xml
    #     - php-zip

    #=====[ MySQL ]=====
#ハマりにハマったんで、MySQLは一旦休止。
#
#    - name: install mysql
#      command: sudo rpm -ivh {{mysql_repo_url}}
#      command: echo "If there is no suitable command here, I get an error after executing the above command! I wonder why!"
#    - name: install mysql
#      yum: name={{item}} state=present
#      with_items:
#        - mysql-community-server
#
#    - name: create mysql database
#      mysql_db: name={{ mysql_database }} state=present
#    - name: create mysql user
#      #mysql_user: name={{ mysql_user }} host={{ item }} password={{ mysql_password }} priv={{ mysql_database }}.*:ALL,GRANT state=present
#      mysql_user: name={{ mysql_user }} host={{ item }} password={{ mysql_password }} priv=*.*:ALL,GRANT state=present
#      with_items:
#        - localhost
#        #- 192.168.10.%
#    - name: uncomment a line bind-address = 127.0.0.1
#      replace: >
#        dest=/etc/mysql/mysql.conf.d/mysqld.cnf
#        regexp='^bind-address'
#        replace='#bind-address'
#    - name: start mysql
#      service: name=mysql state=restarted enabled=yes
#
#    - name: restart mysql
#      command: sudo systemctl restart mysqld.service
#      command: echo "If there is no suitable command here, I get an error after executing the above command! I wonder why!"

