#!/bin/bash

echo "Git Installing..."
sudo yum install -y git

echo "aws-cli Installing..."
sudo yum install -y aws-cli

echo "Node.js Installing..."
sudo curl -sSL https://rpm.nodesource.com/setup_16.x | bash -
sudo yum install -y nodejs

echo "PHP Installing..."
amazon-linux-extras enable php8.0
sudo yum install -y php
sudo yum install -y php-mbstring php-devel

# amazon-linux-extras enable
