#!/bin/bash

echo "Git Installing..."
sudo yum install -y git

echo "aws-cli Installing..."
sudo yum install -y aws-cli

echo "Node.js Installing..."
sudo curl -sSL https://rpm.nodesource.com/setup_16.x | bash -
sudo yum install -y nodejs

echo "PHP Installing..."
amazon-linux-extras enable php8.0
sudo yum install -y php
sudo yum install -y php-bcmath php-dom php-gd php-mbstring php-mysqli php-posix php-sodium php-opcache
sudo yum install -y php-devel

echo "Composer Installing..."
sudo curl -sS https://getcomposer.org/installer | sudo php
sudo mv composer.phar /usr/local/bin/composer
sudo ln -s /usr/local/bin/composer /usr/bin/composer

echo "Nginx Installing..."
amazon-linux-extras enable nginx1
yum install -y nginx



